// TestRunner.cpp - Main test runner for EndKey comprehensive testing
// Created by Hive-Tester-001 for EndKey refactoring validation

#include <gtest/gtest.h>
#include <iostream>
#include <string>
#include <vector>
#include <chrono>
#include <fstream>
#include <memory>

// Include all test headers
#include "VietnameseInputTest.cpp"
#include "PerformanceBenchmark.cpp"
#include "MacroSystemTest.cpp"
#include "IntegrationTest.cpp"
#include "CrossPlatformTest.cpp"
#include "UserAcceptanceTest.cpp"

// Test result reporting
struct TestResults {
    int totalTests;
    int passedTests;
    int failedTests;
    int skippedTests;
    std::chrono::milliseconds totalTime;
    std::vector<std::string> failedTestNames;
    std::vector<std::string> performanceMetrics;
};

class TestReporter {
private:
    TestResults results;
    std::chrono::steady_clock::time_point startTime;
    std::ofstream reportFile;

public:
    TestReporter() : results({0, 0, 0, 0, std::chrono::milliseconds(0), {}, {}}) {
        startTime = std::chrono::steady_clock::now();
        reportFile.open("/Users/dta.business/Desktop/dev/EndKey/tests/test_report.md");
        writeReportHeader();
    }

    ~TestReporter() {
        writeReportFooter();
        if (reportFile.is_open()) {
            reportFile.close();
        }
    }

    void updateResults(int total, int passed, int failed, int skipped) {
        results.totalTests = total;
        results.passedTests = passed;
        results.failedTests = failed;
        results.skippedTests = skipped;

        auto endTime = std::chrono::steady_clock::now();
        results.totalTime = std::chrono::duration_cast<std::chrono::milliseconds>(endTime - startTime);
    }

    void addFailedTest(const std::string& testName) {
        results.failedTestNames.push_back(testName);
    }

    void addPerformanceMetric(const std::string& metric) {
        results.performanceMetrics.push_back(metric);
    }

    void generateReport() {
        writeSummary();
        writeDetailedResults();
        writePerformanceAnalysis();
        writeRecommendations();
    }

    TestResults getResults() const {
        return results;
    }

private:
    void writeReportHeader() {
        if (reportFile.is_open()) {
            reportFile << "# EndKey Test Report\n\n";
            reportFile << "**Generated:** " << getCurrentTimestamp() << "\n";
            reportFile << "**Test Agent:** Hive-Tester-001\n";
            reportFile << "**Purpose:** Comprehensive testing for EndKey refactoring validation\n\n";
        }
    }

    void writeReportFooter() {
        if (reportFile.is_open()) {
            reportFile << "\n---\n";
            reportFile << "*Report generated by EndKey Test Runner*\n";
        }
    }

    void writeSummary() {
        if (reportFile.is_open()) {
            reportFile << "## Test Summary\n\n";
            reportFile << "- **Total Tests:** " << results.totalTests << "\n";
            reportFile << "- **Passed:** " << results.passedTests << " ("
                      << (results.totalTests > 0 ? (results.passedTests * 100 / results.totalTests) : 0) << "%)\n";
            reportFile << "- **Failed:** " << results.failedTests << " ("
                      << (results.totalTests > 0 ? (results.failedTests * 100 / results.totalTests) : 0) << "%)\n";
            reportFile << "- **Skipped:** " << results.skippedTests << "\n";
            reportFile << "- **Total Time:** " << results.totalTime.count() << "ms\n\n";

            // Status indicator
            if (results.failedTests == 0) {
                reportFile << "✅ **ALL TESTS PASSED**\n\n";
            } else {
                reportFile << "❌ **TESTS FAILED** - " << results.failedTests << " test(s) failed\n\n";
            }
        }
    }

    void writeDetailedResults() {
        if (reportFile.is_open()) {
            reportFile << "## Detailed Results\n\n";

            if (!results.failedTestNames.empty()) {
                reportFile << "### Failed Tests\n\n";
                for (const auto& testName : results.failedTestNames) {
                    reportFile << "- ❌ " << testName << "\n";
                }
                reportFile << "\n";
            } else {
                reportFile << "### All Tests Passed\n\n";
                reportFile << "✅ No test failures detected.\n\n";
            }
        }
    }

    void writePerformanceAnalysis() {
        if (reportFile.is_open()) {
            reportFile << "## Performance Analysis\n\n";

            if (!results.performanceMetrics.empty()) {
                reportFile << "### Performance Metrics\n\n";
                for (const auto& metric : results.performanceMetrics) {
                    reportFile << "- " << metric << "\n";
                }
                reportFile << "\n";
            } else {
                reportFile << "No performance metrics collected.\n\n";
            }
        }
    }

    void writeRecommendations() {
        if (reportFile.is_open()) {
            reportFile << "## Recommendations\n\n";

            if (results.failedTests == 0) {
                reportFile << "### ✅ Refactoring Validation\n\n";
                reportFile << "The refactoring appears to be **successful** with all tests passing. ";
                reportFile << "The system maintains existing functionality while enabling the planned improvements.\n\n";
                reportFile << "### Next Steps\n\n";
                reportFile << "1. **Deploy to staging environment** for further testing\n";
                reportFile << "2. **Conduct user acceptance testing** with real users\n";
                reportFile << "3. **Monitor performance** in production environment\n";
                reportFile << "4. **Plan next refactoring phase** based on results\n\n";
            } else {
                reportFile << "### ⚠️ Refactoring Issues Detected\n\n";
                reportFile << "The refactoring has **issues** that need to be addressed before deployment:\n\n";
                reportFile << "1. **Fix failing tests** - Address all test failures\n";
                reportFile << "2. **Review code changes** - Identify root causes\n";
                reportFile << "3. **Performance optimization** - Address any performance regressions\n";
                reportFile << "4. **Re-run comprehensive tests** after fixes\n\n";
            }

            reportFile << "### Quality Assurance Checklist\n\n";
            reportFile << "- [ ] All unit tests passing\n";
            reportFile << "- [ ] Integration tests successful\n";
            reportFile << "- [ ] Performance benchmarks met\n";
            reportFile << "- [ ] Cross-platform compatibility verified\n";
            reportFile << "- [ ] User acceptance criteria met\n";
            reportFile << "- [ ] Memory leak detection passed\n";
            reportFile << "- [ ] Security validation completed\n\n";
        }
    }

    std::string getCurrentTimestamp() {
        auto now = std::chrono::system_clock::now();
        auto time_t = std::chrono::system_clock::to_time_t(now);
        std::stringstream ss;
        ss << std::put_time(std::localtime(&time_t), "%Y-%m-%d %H:%M:%S");
        return ss.str();
    }
};

// Custom test event listener for reporting
class EndKeyTestListener : public ::testing::EmptyTestEventListener {
private:
    TestReporter* reporter;

public:
    EndKeyTestListener(TestReporter* rep) : reporter(rep) {}

    void OnTestStart(const ::testing::TestInfo& test_info) override {
        std::cout << "Running: " << test_info.test_case_name() << "." << test_info.name() << std::endl;
    }

    void OnTestEnd(const ::testing::TestInfo& test_info) override {
        if (test_info.result()->Failed()) {
            std::string testName = std::string(test_info.test_case_name()) + "." + test_info.name();
            reporter->addFailedTest(testName);
            std::cout << "FAILED: " << testName << std::endl;
        } else {
            std::cout << "PASSED: " << test_info.test_case_name() << "." << test_info.name() << std::endl;
        }
    }

    void OnTestProgramEnd(const ::testing::UnitTest& unit_test) override {
        int total = unit_test.total_test_count();
        int passed = unit_test.successful_test_count();
        int failed = unit_test.failed_test_count();
        int skipped = unit_test.disabled_test_count();

        reporter->updateResults(total, passed, failed, skipped);

        std::cout << "\n=== Test Summary ===" << std::endl;
        std::cout << "Total Tests: " << total << std::endl;
        std::cout << "Passed: " << passed << std::endl;
        std::cout << "Failed: " << failed << std::endl;
        std::cout << "Skipped: " << skipped << std::endl;

        if (failed == 0) {
            std::cout << "✅ ALL TESTS PASSED!" << std::endl;
        } else {
            std::cout << "❌ " << failed << " TESTS FAILED!" << std::endl;
        }
    }
};

// Performance monitoring
class PerformanceMonitor {
private:
    std::chrono::steady_clock::time_point testSuiteStart;
    std::vector<std::pair<std::string, std::chrono::milliseconds>> testTimes;
    TestReporter* reporter;

public:
    PerformanceMonitor(TestReporter* rep) : reporter(rep) {
        testSuiteStart = std::chrono::steady_clock::now();
    }

    void recordTestTime(const std::string& testName, std::chrono::milliseconds duration) {
        testTimes.push_back({testName, duration});
    }

    void analyzePerformance() {
        if (testTimes.empty()) return;

        auto totalTime = std::chrono::steady_clock::now() - testSuiteStart;
        auto totalMs = std::chrono::duration_cast<std::chrono::milliseconds>(totalTime);

        reporter->addPerformanceMetric("Total Test Suite Time: " + std::to_string(totalMs.count()) + "ms");

        // Find slowest tests
        if (testTimes.size() > 0) {
            auto slowest = std::max_element(testTimes.begin(), testTimes.end(),
                [](const auto& a, const auto& b) { return a.second < b.second; });

            reporter->addPerformanceMetric("Slowest Test: " + slowest->first +
                                         " (" + std::to_string(slowest->second.count()) + "ms)");
        }

        // Calculate average test time
        long long totalTestTime = 0;
        for (const auto& test : testTimes) {
            totalTestTime += test.second.count();
        }
        double avgTime = static_cast<double>(totalTestTime) / testTimes.size();

        reporter->addPerformanceMetric("Average Test Time: " + std::to_string(avgTime) + "ms");
    }
};

// Test suite configuration
struct TestSuiteConfig {
    bool runUnitTests = true;
    bool runPerformanceTests = true;
    bool runIntegrationTests = true;
    bool runCrossPlatformTests = true;
    bool runUserAcceptanceTests = true;
    bool enableVerboseOutput = false;
    std::string outputFormat = "console"; // console, xml, json
};

// Main test runner
class EndKeyTestRunner {
private:
    TestSuiteConfig config;
    std::unique_ptr<TestReporter> reporter;
    std::unique_ptr<PerformanceMonitor> perfMonitor;

public:
    EndKeyTestRunner(const TestSuiteConfig& cfg) : config(cfg) {
        reporter = std::make_unique<TestReporter>();
        perfMonitor = std::make_unique<PerformanceMonitor>(reporter.get());
    }

    int runTests(int argc, char** argv) {
        std::cout << "=== EndKey Comprehensive Test Runner ===" << std::endl;
        std::cout << "Agent: Hive-Tester-001" << std::endl;
        std::cout << "Purpose: EndKey refactoring validation" << std::endl;
        std::cout << "========================================" << std::endl;

        // Initialize Google Test
        ::testing::InitGoogleTest(&argc, argv);

        // Set up custom listener
        ::testing::TestEventListeners& listeners = ::testing::UnitTest::GetInstance()->listeners();
        listeners.Append(new EndKeyTestListener(reporter.get()));

        // Configure test filters based on config
        if (!config.runUnitTests) {
            ::testing::GTEST_FLAG(filter) = "-VietnameseInputTest.*:MacroSystemTest.*";
        }
        if (!config.runPerformanceTests) {
            ::testing::GTEST_FLAG(filter) += ":PerformanceTest.*";
        }
        if (!config.runIntegrationTests) {
            ::testing::GTEST_FLAG(filter) += ":IntegrationTest.*";
        }
        if (!config.runCrossPlatformTests) {
            ::testing::GTEST_FLAG(filter) += ":CrossPlatformTest.*";
        }
        if (!config.runUserAcceptanceTests) {
            ::testing::GTEST_FLAG(filter) += ":UserAcceptanceTest.*";
        }

        // Run tests
        auto testStart = std::chrono::high_resolution_clock::now();
        int result = RUN_ALL_TESTS();
        auto testEnd = std::chrono::high_resolution_clock::now();

        // Analyze performance
        perfMonitor->analyzePerformance();

        // Generate comprehensive report
        reporter->generateReport();

        // Print final summary
        printFinalSummary(result, testEnd - testStart);

        return result;
    }

private:
    void printFinalSummary(int testResult, std::chrono::milliseconds totalTime) {
        std::cout << "\n=== Final Test Summary ===" << std::endl;
        std::cout << "Test Result: " << (testResult == 0 ? "✅ PASSED" : "❌ FAILED") << std::endl;
        std::cout << "Total Time: " << totalTime.count() << "ms" << std::endl;
        std::cout << "Report Generated: /Users/dta.business/Desktop/dev/EndKey/tests/test_report.md" << std::endl;
        std::cout << "=========================" << std::endl;

        if (testResult == 0) {
            std::cout << "\n🎉 EndKey refactoring validation SUCCESSFUL!" << std::endl;
            std::cout << "All tests passed. The refactoring maintains existing functionality." << std::endl;
            std::cout << "Ready for next phase of development." << std::endl;
        } else {
            std::cout << "\n⚠️ EndKey refactoring validation FAILED!" << std::endl;
            std::cout << "Some tests failed. Please review the report and fix issues." << std::endl;
            std::cout << "Do not proceed with deployment until all issues are resolved." << std::endl;
        }
    }
};

// Command line argument parsing
TestSuiteConfig parseCommandLine(int argc, char** argv) {
    TestSuiteConfig config;

    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];

        if (arg == "--no-unit") {
            config.runUnitTests = false;
        } else if (arg == "--no-performance") {
            config.runPerformanceTests = false;
        } else if (arg == "--no-integration") {
            config.runIntegrationTests = false;
        } else if (arg == "--no-crossplatform") {
            config.runCrossPlatformTests = false;
        } else if (arg == "--no-uat") {
            config.runUserAcceptanceTests = false;
        } else if (arg == "--verbose") {
            config.enableVerboseOutput = true;
            ::testing::GTEST_FLAG(print_time) = true;
            ::testing::GTEST_FLAG(print_utf8) = true;
        } else if (arg == "--xml-output") {
            config.outputFormat = "xml";
            ::testing::GTEST_FLAG(output) = "xml:test_results.xml";
        } else if (arg == "--json-output") {
            config.outputFormat = "json";
            ::testing::GTEST_FLAG(output) = "json:test_results.json";
        } else if (arg == "--help") {
            std::cout << "EndKey Test Runner - Usage:\n";
            std::cout << "  --no-unit          Skip unit tests\n";
            std::cout << "  --no-performance   Skip performance tests\n";
            std::cout << "  --no-integration   Skip integration tests\n";
            std::cout << "  --no-crossplatform Skip cross-platform tests\n";
            std::cout << "  --no-uat           Skip user acceptance tests\n";
            std::cout << "  --verbose          Enable verbose output\n";
            std::cout << "  --xml-output       Generate XML report\n";
            std::cout << "  --json-output      Generate JSON report\n";
            std::cout << "  --help             Show this help\n";
            exit(0);
        }
    }

    return config;
}

int main(int argc, char** argv) {
    try {
        // Parse command line arguments
        TestSuiteConfig config = parseCommandLine(argc, argv);

        // Create and run test suite
        EndKeyTestRunner runner(config);
        return runner.runTests(argc, argv);

    } catch (const std::exception& e) {
        std::cerr << "Test runner error: " << e.what() << std::endl;
        return 1;
    } catch (...) {
        std::cerr << "Unknown test runner error occurred" << std::endl;
        return 1;
    }
}